// <auto-generated />
using System;
using K2_EducationProgramClient.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace K2_EducationProgramClient.Migrations
{
    [DbContext(typeof(EducationProgramClientDbContext))]
    [Migration("20251214221959_AddTeacherCourseAndEnrollmentSeedData")]
    partial class AddTeacherCourseAndEnrollmentSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("K2_EducationProgramClient.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<DateOnly>("ActiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ActiveTo")
                        .HasColumnType("date");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseID = 1,
                            ActiveFrom = new DateOnly(2025, 1, 1),
                            CourseName = "Mathematics 1",
                            CourseStatus = "Active"
                        },
                        new
                        {
                            CourseID = 2,
                            ActiveFrom = new DateOnly(2025, 1, 1),
                            CourseName = "Programming C#",
                            CourseStatus = "Active"
                        },
                        new
                        {
                            CourseID = 3,
                            ActiveFrom = new DateOnly(2025, 1, 1),
                            CourseName = "Swedish Literature",
                            CourseStatus = "Active"
                        },
                        new
                        {
                            CourseID = 4,
                            ActiveFrom = new DateOnly(2025, 1, 1),
                            CourseName = "World Geography",
                            CourseStatus = "Active"
                        });
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentID"));

                    b.Property<DateOnly>("EnrollmentDate")
                        .HasColumnType("date");

                    b.Property<int>("FkCourseID")
                        .HasColumnType("int");

                    b.Property<int>("FkStudentID")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("FkCourseID");

                    b.HasIndex("FkStudentID");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentID = 1,
                            EnrollmentDate = new DateOnly(1, 1, 1),
                            FkCourseID = 1,
                            FkStudentID = 1
                        },
                        new
                        {
                            EnrollmentID = 2,
                            EnrollmentDate = new DateOnly(1, 1, 1),
                            FkCourseID = 2,
                            FkStudentID = 2
                        },
                        new
                        {
                            EnrollmentID = 3,
                            EnrollmentDate = new DateOnly(1, 1, 1),
                            FkCourseID = 1,
                            FkStudentID = 3
                        },
                        new
                        {
                            EnrollmentID = 4,
                            EnrollmentDate = new DateOnly(1, 1, 1),
                            FkCourseID = 2,
                            FkStudentID = 4
                        });
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Grade", b =>
                {
                    b.Property<int>("GradeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeID"));

                    b.Property<int>("FkEnrollmentID")
                        .HasColumnType("int");

                    b.Property<int>("FkTeacherID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("GradeDate")
                        .HasColumnType("date");

                    b.Property<string>("GradeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradeID");

                    b.HasIndex("FkEnrollmentID");

                    b.HasIndex("FkTeacherID");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeID = 1,
                            FkEnrollmentID = 1,
                            FkTeacherID = 1,
                            GradeDate = new DateOnly(2025, 12, 15),
                            GradeValue = "A"
                        },
                        new
                        {
                            GradeID = 2,
                            FkEnrollmentID = 2,
                            FkTeacherID = 2,
                            GradeDate = new DateOnly(2025, 12, 16),
                            GradeValue = "B"
                        },
                        new
                        {
                            GradeID = 3,
                            FkEnrollmentID = 3,
                            FkTeacherID = 2,
                            GradeDate = new DateOnly(2025, 12, 17),
                            GradeValue = "C"
                        },
                        new
                        {
                            GradeID = 4,
                            FkEnrollmentID = 4,
                            FkTeacherID = 1,
                            GradeDate = new DateOnly(2025, 12, 18),
                            GradeValue = "B"
                        });
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomID = 1,
                            Capacity = 30,
                            RoomName = "A101"
                        },
                        new
                        {
                            RoomID = 2,
                            Capacity = 25,
                            RoomName = "B202"
                        });
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FkRoomID")
                        .HasColumnType("int");

                    b.Property<int>("FkTeacherCourseID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleID");

                    b.HasIndex("FkRoomID");

                    b.HasIndex("FkTeacherCourseID");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            ScheduleID = 1,
                            Date = new DateOnly(2025, 12, 15),
                            EndTime = new DateTime(2025, 12, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            FkRoomID = 1,
                            FkTeacherCourseID = 1,
                            StartTime = new DateTime(2025, 12, 15, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleID = 2,
                            Date = new DateOnly(2025, 12, 16),
                            EndTime = new DateTime(2025, 12, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            FkRoomID = 2,
                            FkTeacherCourseID = 2,
                            StartTime = new DateTime(2025, 12, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StudentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            Email = "adchariya.changtam@example.com",
                            FirstName = "Adchariya",
                            LastName = "Changtam",
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            StudentID = 2,
                            Email = "coday.awahmed@example.com",
                            FirstName = "Coday",
                            LastName = "Awahmed",
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            StudentID = 3,
                            Email = "hande.bengu@example.com",
                            FirstName = "Hande",
                            LastName = "Bengu",
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            StudentID = 4,
                            Email = "jordan.foose@example.com",
                            FirstName = "Jordan",
                            LastName = "Foose",
                            StartDate = new DateOnly(1, 1, 1)
                        });
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherID");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherID = 1,
                            Email = "eva.eriksson@example.com",
                            FirstName = "Eva",
                            LastName = "Eriksson"
                        },
                        new
                        {
                            TeacherID = 2,
                            Email = "david.dahl@example.com",
                            FirstName = "David",
                            LastName = "Dahl"
                        });
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.TeacherCourse", b =>
                {
                    b.Property<int>("TeacherCourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherCourseID"));

                    b.Property<int>("FkCourseID")
                        .HasColumnType("int");

                    b.Property<int>("FkTeacherID")
                        .HasColumnType("int");

                    b.HasKey("TeacherCourseID");

                    b.HasIndex("FkCourseID");

                    b.HasIndex("FkTeacherID");

                    b.ToTable("TeacherCourses");

                    b.HasData(
                        new
                        {
                            TeacherCourseID = 1,
                            FkCourseID = 1,
                            FkTeacherID = 1
                        },
                        new
                        {
                            TeacherCourseID = 2,
                            FkCourseID = 2,
                            FkTeacherID = 2
                        });
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Enrollment", b =>
                {
                    b.HasOne("K2_EducationProgramClient.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("FkCourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K2_EducationProgramClient.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("FkStudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Grade", b =>
                {
                    b.HasOne("K2_EducationProgramClient.Models.Enrollment", "Enrollment")
                        .WithMany("Grades")
                        .HasForeignKey("FkEnrollmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K2_EducationProgramClient.Models.Teacher", "Teacher")
                        .WithMany("GradesGiven")
                        .HasForeignKey("FkTeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Schedule", b =>
                {
                    b.HasOne("K2_EducationProgramClient.Models.Room", "Room")
                        .WithMany("Schedules")
                        .HasForeignKey("FkRoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K2_EducationProgramClient.Models.TeacherCourse", "TeacherCourse")
                        .WithMany("Schedules")
                        .HasForeignKey("FkTeacherCourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("TeacherCourse");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.TeacherCourse", b =>
                {
                    b.HasOne("K2_EducationProgramClient.Models.Course", "Course")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("FkCourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K2_EducationProgramClient.Models.Teacher", "Teacher")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("FkTeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("TeacherCourses");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Enrollment", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Room", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Teacher", b =>
                {
                    b.Navigation("GradesGiven");

                    b.Navigation("TeacherCourses");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.TeacherCourse", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
