// <auto-generated />
using System;
using K2_EducationProgramClient.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace K2_EducationProgramClient.Migrations
{
    [DbContext(typeof(EducationProgramClientDbContext))]
    partial class EducationProgramClientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("K2_EducationProgramClient.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<DateOnly>("ActiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ActiveTo")
                        .HasColumnType("date");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentID"));

                    b.Property<DateOnly>("EnrollmentDate")
                        .HasColumnType("date");

                    b.Property<int>("FkCourseID")
                        .HasColumnType("int");

                    b.Property<int>("FkStudentID")
                        .HasColumnType("int");

                    b.Property<int?>("GradeID")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("FkCourseID");

                    b.HasIndex("FkStudentID");

                    b.HasIndex("GradeID");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Grade", b =>
                {
                    b.Property<int>("GradeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeID"));

                    b.Property<int>("FkEnrollmentID")
                        .HasColumnType("int");

                    b.Property<int>("FkTeacherID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("GradeDate")
                        .HasColumnType("date");

                    b.Property<string>("GradeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradeID");

                    b.HasIndex("FkEnrollmentID");

                    b.HasIndex("FkTeacherID");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("FkCourseID")
                        .HasColumnType("int");

                    b.Property<int>("FkRoomID")
                        .HasColumnType("int");

                    b.Property<int>("FkTeacherID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ScheduleID");

                    b.HasIndex("FkCourseID");

                    b.HasIndex("FkRoomID");

                    b.HasIndex("FkTeacherID");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StudentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherID");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Enrollment", b =>
                {
                    b.HasOne("K2_EducationProgramClient.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("FkCourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K2_EducationProgramClient.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("FkStudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K2_EducationProgramClient.Models.Grade", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("GradeID");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Grade", b =>
                {
                    b.HasOne("K2_EducationProgramClient.Models.Enrollment", "Enrollment")
                        .WithMany()
                        .HasForeignKey("FkEnrollmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K2_EducationProgramClient.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("FkTeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Schedule", b =>
                {
                    b.HasOne("K2_EducationProgramClient.Models.Course", "Course")
                        .WithMany("Schedules")
                        .HasForeignKey("FkCourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K2_EducationProgramClient.Models.Room", "Room")
                        .WithMany("Schedules")
                        .HasForeignKey("FkRoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K2_EducationProgramClient.Models.Teacher", "Teacher")
                        .WithMany("Schedules")
                        .HasForeignKey("FkTeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Room");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Grade", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Room", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("K2_EducationProgramClient.Models.Teacher", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
